[tool.poetry]
name = "data311"
version = "0.1.0"
description = ""
authors = ["Arthur-Huan <c.arthurh@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.x"
typer = "0.9.0"
bcrypt = "4.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
